name: Publish to TestPyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.2.0
      - run: uv build
      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/


  test-pypi:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pypi-publish-test
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: false
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      # - run: uv build
      - run: uv publish --publish-url https://test.pypi.org/legacy/
    
  pypi:
    needs: test-pypi
    runs-on: ubuntu-latest
    environment:
      # Add yourself as a required reviewer on this environment to approve
      # each PyPI upload by hand.
      name: pypi
      url: https://pypi.org/p/pypi-publish-test
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: false
      # - run: uv build
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/
      - run: uv publish --publish-url https://pypi.org/

