name: Publish to TestPyPI

on:
  release:
    types: [published]

jobs:
  test-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/zensical-dirtree
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: false
      - run: uv build
      - run: uv publish --publish-url https://test.pypi.org/legacy/
    
  pypi:
    runs-on: ubuntu-latest
    environment:
      # Add yourself as a required reviewer on this environment to approve
      # each PyPI upload by hand.
      name: pypi
      url: https://pypi.org/p/zensical-dirtree
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: false
      - run: uv build
      - run: uv publish --publish-url https://test.pypi.org/legacy/
    
